"""removing shelf no and coverimage colomn from book

Revision ID: ab753d99aa46
Revises: d0955186f929
Create Date: 2026-07-08 17:33:01.131919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab753d99aa46'
down_revision: Union[str, Sequence[str], None] = 'd0955186f929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'shelf_number')
    op.drop_column('books', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('shelf_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
